### ISSUE TITLE
python controller.py -  errors  - Exception: Didn't pick a model. Should run ps instead.

### ISSUE THREAD

**Issue by johndpope** [mattiasarro/seq2seq-cvae-tensorflow#6]
```shell
python controller.py
Train stages: ['vae_uncond', 'classify', 'vae_cond_lab', 'classify_synth']
WARNING:tensorflow:From controller.py:24: RunConfig.__init__ (from tensorflow.contrib.learn.python.learn.estimators.run_config) is deprecated and will be removed in a future version.
Instructions for updating:
When switching to tf.estimator.Estimator, use tf.estimator.RunConfig instead.
WARNING:tensorflow:From controller.py:31: run (from tensorflow.contrib.learn.python.learn.learn_runner) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.estimator.train_and_evaluate.
WARNING:tensorflow:RunConfig.uid (from tensorflow.contrib.learn.python.learn.estimators.run_config) is experimental and may change or be removed at any time, and without warning.
Traceback (most recent call last):
  File "controller.py", line 117, in <module>
    tf.app.run(main=train)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "controller.py", line 31, in train
    hparams=hparams
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 208, in run
    experiment = wrapped_experiment_fn(run_config=run_config, hparams=hparams)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 85, in wrapped_experiment_fn
    experiment = experiment_fn(run_config, hparams)
  File "controller.py", line 66, in experiment_fn
    model_class = get_model_class(run_config)
  File "controller.py", line 19, in get_model_class
    raise Exception("Didn't pick a model. Should run ps instead.")
Exception: Didn't pick a model. Should run ps instead.
```

**Comment by johndpope** [comment]
if I replace  get_model_class to force return VAECondModel 


```python
def get_model_class(run_config):
    if run_config.task_type in ["worker"]:
        model_name = hparams.worker_processes[run_config.task_id]
        model_class = eval(model_name)
        print("-- -- worker " + str(run_config.task_id) + " , model " + model_class.__name__)
        return model_class
    else:
        return eval("VAECondModel")
```


this progresses things.
