### ISSUE TITLE
python controller.py blows up (after dropping in train test set from acl-imdb-v1 + hacking model to return VAECondModel) 

### ISSUE THREAD

**Issue by johndpope** [mattiasarro/seq2seq-cvae-tensorflow#8]
-- (train) kl_weight [4.53978719e-05][1]
-- (train) TASK [vae_cond_lab]
-- src_seq_emb passing thru enc bi --[vae_cond_lab][1]
-- (train) kl_loss [1.39073318e-05][1]
-- src_seq_emb passing thru enc bi --[vae_cond_lab][1]
-- src_seq_emb passing thru enc bi --[vae_cond_lab][1]
Traceback (most recent call last):
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: seq_lens(0) > input.dims(1)
	 [[Node: Encoder_1/bidirectional/bidirectional_rnn/bw/ReverseSequence = ReverseSequence[T=DT_FLOAT, Tlen=DT_INT32, batch_dim=0, seq_dim=1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Encoder_1/bidirectional/Print, Squeeze)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "controller.py", line 118, in <module>
    tf.app.run(main=train)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "controller.py", line 32, in train
    hparams=hparams
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 225, in run
    return _execute_schedule(experiment, schedule)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 52, in _execute_schedule
    return task()
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 389, in train
    saving_listeners=self._saving_listeners)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 876, in _call_train
    saving_listeners=saving_listeners)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 363, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 843, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 859, in _train_model_default
    saving_listeners)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1059, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 567, in run
    run_metadata=run_metadata)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1043, in run
    run_metadata=run_metadata)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1134, in run
    raise six.reraise(*original_exc_info)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1119, in run
    return self._sess.run(*args, **kwargs)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1191, in run
    run_metadata=run_metadata)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 971, in run
    return self._sess.run(*args, **kwargs)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: seq_lens(0) > input.dims(1)
	 [[Node: Encoder_1/bidirectional/bidirectional_rnn/bw/ReverseSequence = ReverseSequence[T=DT_FLOAT, Tlen=DT_INT32, batch_dim=0, seq_dim=1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Encoder_1/bidirectional/Print, Squeeze)]]

Caused by op 'Encoder_1/bidirectional/bidirectional_rnn/bw/ReverseSequence', defined at:
  File "controller.py", line 118, in <module>
    tf.app.run(main=train)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "controller.py", line 32, in train
    hparams=hparams
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 225, in run
    return _execute_schedule(experiment, schedule)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 52, in _execute_schedule
    return task()
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 389, in train
    saving_listeners=self._saving_listeners)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 876, in _call_train
    saving_listeners=saving_listeners)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 363, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 843, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 856, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 831, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "controller.py", line 95, in model_fn
    hparams=params
  File "/Users/jpope/Documents/tensorflowWorkspace/seq2seq-cvae-tensorflow/model.py", line 281, in __init__
    self.init_model()
  File "/Users/jpope/Documents/tensorflowWorkspace/seq2seq-cvae-tensorflow/model.py", line 450, in init_model
    input_embs=self.decoder_soft.avg_emb,
  File "/Users/jpope/Documents/tensorflowWorkspace/seq2seq-cvae-tensorflow/model.py", line 19, in reuse_params
    return cls.get_model(True, *args, **kwargs)
  File "/Users/jpope/Documents/tensorflowWorkspace/seq2seq-cvae-tensorflow/model.py", line 24, in get_model
    component = cls(*args, **kwargs)
  File "/Users/jpope/Documents/tensorflowWorkspace/seq2seq-cvae-tensorflow/model.py", line 41, in __init__
    self._init_bidirectional(cell)
  File "/Users/jpope/Documents/tensorflowWorkspace/seq2seq-cvae-tensorflow/model.py", line 55, in _init_bidirectional
    dtype=tf.float32)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 433, in bidirectional_dynamic_rnn
    seq_dim=time_dim, batch_dim=batch_dim)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 426, in _reverse
    seq_dim=seq_dim, batch_dim=batch_dim)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2712, in reverse_sequence
    name=name)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6449, in reverse_sequence
    seq_dim=seq_dim, batch_dim=batch_dim, name=name)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): seq_lens(0) > input.dims(1)
	 [[Node: Encoder_1/bidirectional/bidirectional_rnn/bw/ReverseSequence = ReverseSequence[T=DT_FLOAT, Tlen=DT_INT32, batch_dim=0, seq_dim=1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Encoder_1/bidirectional/Print, Squeeze)]]

**Comment by johndpope** [comment]
seems fine with ClassifierSynthModel
def get_model_class(run_config):
    if run_config.task_type in ["worker"]:
        model_name = hparams.worker_processes[run_config.task_id]
        model_class = eval(model_name)
        print("-- -- worker " + str(run_config.task_id) + " , model " + model_class.__name__)
        return model_class
    else:
        return eval("ClassifierSynthModel")

**Comment by johndpope** [comment]
[classify_synth]
-- src_seq_emb passing thru enc bi --[classify_synth][176]
-- (train) synth_class_entropy [124.814819][176]
-- (train) classify_synth_loss [-120.848076][176]
-- (train) TASK [classify_synth]
-- src_seq_emb passing thru enc bi --[classify_synth][177]
-- (train) synth_class_entropy [125.280739][177]
-- (train) classify_synth_loss [-120.525253][177]
-- (train) TASK [classify_synth]
-- src_seq_emb passing thru enc bi --[classify_synth][178]
-- (train) synth_class_entropy [125.774162][178]
-- (train) classify_synth_loss [-121.801712][178]
INFO:tensorflow:Saving checkpoints for 178 into ./models/imdb/model.ckpt.
-- (train) TASK [classify_synth]
-- src_seq_emb passing thru enc bi --[classify_synth][179]
-- (train) synth_class_entropy [126.408539][179]
-- (train) classify_synth_loss [-121.648674][179]
-- (train) TASK [classify_synth]
-- src_seq_emb passing thru enc bi --[classify_synth][180]
-- (train) synth_class_entropy [126.719566][180]
-- (train) classify_synth_loss [-122.756363][180]
-- (train) TASK [classify_synth]
-- src_seq_emb passing thru enc bi --[classify_synth][181]
-- (train) synth_class_entropy [127.525398][181]
-- (train) classify_synth_loss [-124.350479][181]
INFO:tensorflow:Saving checkpoints for 181 into ./models/imdb/model.ckpt.
-- (train) TASK [classify_synth]
-- src_seq_emb passing thru enc bi --[classify_synth][182]
-- (train) synth_class_entropy [127.974739][182]
-- (train) classify_synth_loss [-126.385612][182]
-- (train) TASK [classify_synth]
-- src_seq_emb passing thru enc bi --[classify_synth][183]
-- (train) synth_class_entropy [128.58078][183]
-- (train) classify_synth_loss [-123.81031][183]
-- (train) TASK [classify_synth]
-- src_seq_emb passing thru enc bi --[classify_synth][184]
-- (train) synth_class_entropy [128.923645][184]
-- (train) classify_synth_loss [-123.354675][184]
INFO:tensorflow:Saving checkpoints for 184 into ./models/imdb/model.ckpt.
-- (train) TASK [classify_synth]
-- src_seq_emb passing thru enc bi --[classify_synth][185]
-- (train) synth_class_entropy [129.681732][185]
-- (train) classify_synth_loss [-126.499786][185]
-- (train) TASK [classify_synth]
-- src_seq_emb passing thru enc bi --[classify_synth][186]
-- (train) synth_class_entropy [130.22139][186]
-- (train) classify_synth_loss [-125.439163][186]
-- (train) TASK [classify_synth]
-- src_seq_emb passing thru enc bi --[classify_synth][187]
-- (train) synth_class_entropy [130.767014][187]
-- (train) classify_synth_loss [-126.780533][187]
INFO:tensorflow:Saving checkpoints for 187 into ./models/imdb/model.ckpt.
-- (train) TASK [classify_synth]
-- src_seq_emb passing thru enc bi --[classify_synth][188]
-- (train) synth_class_entropy [131.044037][188]
-- (train) classify_synth_loss [-124.674843][188]
-- (train) TASK [classify_synth]
-- src_seq_emb passing thru enc bi --[classify_synth][189]
-- (train) synth_class_entropy [131.733765][189]
-- (train) classify_synth_loss [-128.550812][189]
-- (train) TASK [classify_synth]
-- src_seq_emb passing thru enc bi --[classify_synth][190]
-- (train) synth_class_entropy [132.354202][190]
-- (train) classify_synth_loss [-128.367737][190]
INFO:tensorflow:Saving checkpoints for 190 into ./models/imdb/model.ckpt.
-- (train) TASK [classify_synth]
-- src_seq_emb passing thru enc bi --[classify_synth][191]
-- (train) synth_class_entropy [132.798981][191]
